spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food
    username: root
    password: adsfwsx
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update